name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: Format, lint and check Python compatibility
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install vapoursynth-portable==57 pylint yapf vermin
          pip install .

      - name: Format
        run: yapf -q -r ./awsmfunc
      - name: Lint
        run: pylint --rcfile ./.pylintrc ./awsmfunc
      - name: Backwards compatibility
        run: vermin --quiet -vvv --target=3.9 --violations ./awsmfunc
